name: Transport Nepal CI/CD
on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]

jobs: 
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout to Changes
        id: checkout 
        uses: actions/checkout@v2
      
      - name: Setup NodeJS
        id: setup_nodejs
        uses: actions/setup-node@master

      - name: Setup Yarn Cache
        id: setup_yarn_cache
        uses: c-hive/gha-yarn-cache@v1

      - name: Install Dependencies
        id: setup_dependencies
        run: |
          yarn install

      - name: Test Codebase
        id: test
        run: |
          yarn test

  build:
    name: Build Release
    runs-on: ubuntu-latest
    needs: test
    steps: 
      - name: Build Release
        id: build_app
        shell: bash
        run: |
          echo "TODO: Build App"
  
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
      - name: Publish Release
        id: publish
        shell: bash
        run: |
          echo "TODO: Publish App"