name: Transport Nepal CI/CD
on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]

jobs: 
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout to Changes
        id: setup_checkout 
        uses: actions/checkout@v2
      
      - name: Setup NodeJS
        id: setup_nodejs
        uses: actions/setup-node@master

      - name: Setup Yarn Cache
        id: setup_yarn_cache
        uses: c-hive/gha-yarn-cache@v1

      - name: Install Dependencies
        id: setup_dependencies
        run: |
          yarn install

      - name: Test Codebase
        id: test
        run: |
          yarn test --passWithNoTests

      - name: Cache Gradle Wrapper
        id: build_gradle_cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        id: build_cache_dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-


      - name: Build Android Release
        id: build_app
        shell: bash
        run: |
          cd android && chmod +x ./gradlew && ./gradlew bundleRelease --no-daemon
  

      - name: Publish Release
        id: publish_release
        uses: actions/upload-artifact@v2
        with: 
          name: app-release.aab
          path: android/app/build/outputs/bundle/release/app-release.aab 
